// Package httpx provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpx

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
	SetupTokenScopes    setupTokenContextKey    = "SetupToken.Scopes"
)

// Defines values for CompletionProblemField.
const (
	CompletionProblemFieldCompletedOn CompletionProblemField = "completedOn"
	CompletionProblemFieldRecurrence  CompletionProblemField = "recurrence"
	CompletionProblemFieldUndone      CompletionProblemField = "undone"
)

// Valid indicates whether the value is a known member of the CompletionProblemField enum.
func (e CompletionProblemField) Valid() bool {
	switch e {
	case CompletionProblemFieldCompletedOn:
		return true
	case CompletionProblemFieldRecurrence:
		return true
	case CompletionProblemFieldUndone:
		return true
	default:
		return false
	}
}

// Defines values for InvitationRole.
const (
	InvitationRoleMember InvitationRole = "member"
)

// Valid indicates whether the value is a known member of the InvitationRole enum.
func (e InvitationRole) Valid() bool {
	switch e {
	case InvitationRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for InvitationCreatedRole.
const (
	InvitationCreatedRoleMember InvitationCreatedRole = "member"
)

// Valid indicates whether the value is a known member of the InvitationCreatedRole enum.
func (e InvitationCreatedRole) Valid() bool {
	switch e {
	case InvitationCreatedRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for InvitationStatus.
const (
	Accepted InvitationStatus = "accepted"
	Expired  InvitationStatus = "expired"
	Pending  InvitationStatus = "pending"
	Revoked  InvitationStatus = "revoked"
)

// Valid indicates whether the value is a known member of the InvitationStatus enum.
func (e InvitationStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Expired:
		return true
	case Pending:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for InvitationValidationProblemCode.
const (
	InvitationValidationProblemCodeInvalidFormat InvitationValidationProblemCode = "invalid_format"
	InvitationValidationProblemCodeInvalidLength InvitationValidationProblemCode = "invalid_length"
)

// Valid indicates whether the value is a known member of the InvitationValidationProblemCode enum.
func (e InvitationValidationProblemCode) Valid() bool {
	switch e {
	case InvitationValidationProblemCodeInvalidFormat:
		return true
	case InvitationValidationProblemCodeInvalidLength:
		return true
	default:
		return false
	}
}

// Defines values for InvitationValidationProblemField.
const (
	InvitationValidationProblemFieldLogin    InvitationValidationProblemField = "login"
	InvitationValidationProblemFieldPassword InvitationValidationProblemField = "password"
)

// Valid indicates whether the value is a known member of the InvitationValidationProblemField enum.
func (e InvitationValidationProblemField) Valid() bool {
	switch e {
	case InvitationValidationProblemFieldLogin:
		return true
	case InvitationValidationProblemFieldPassword:
		return true
	default:
		return false
	}
}

// Defines values for InvitedAccountRole.
const (
	InvitedAccountRoleMember InvitedAccountRole = "member"
)

// Valid indicates whether the value is a known member of the InvitedAccountRole enum.
func (e InvitedAccountRole) Valid() bool {
	switch e {
	case InvitedAccountRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for ItemAttention.
const (
	NeedsAttention ItemAttention = "needs_attention"
	Upcoming       ItemAttention = "upcoming"
)

// Valid indicates whether the value is a known member of the ItemAttention enum.
func (e ItemAttention) Valid() bool {
	switch e {
	case NeedsAttention:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for ItemValidationProblemCode.
const (
	ItemValidationProblemCodeConflictingFields    ItemValidationProblemCode = "conflicting_fields"
	ItemValidationProblemCodeDateOverflow         ItemValidationProblemCode = "date_overflow"
	ItemValidationProblemCodeFutureDate           ItemValidationProblemCode = "future_date"
	ItemValidationProblemCodeInvalidCharacters    ItemValidationProblemCode = "invalid_characters"
	ItemValidationProblemCodeInvalidDate          ItemValidationProblemCode = "invalid_date"
	ItemValidationProblemCodeInvalidInterval      ItemValidationProblemCode = "invalid_interval"
	ItemValidationProblemCodeInvalidIntervalUnit  ItemValidationProblemCode = "invalid_interval_unit"
	ItemValidationProblemCodeInvalidLength        ItemValidationProblemCode = "invalid_length"
	ItemValidationProblemCodeInvalidMode          ItemValidationProblemCode = "invalid_mode"
	ItemValidationProblemCodeInvalidReference     ItemValidationProblemCode = "invalid_reference"
	ItemValidationProblemCodeInvalidWorkflowState ItemValidationProblemCode = "invalid_workflow_state"
	ItemValidationProblemCodeRequiresRecurrence   ItemValidationProblemCode = "requires_recurrence"
)

// Valid indicates whether the value is a known member of the ItemValidationProblemCode enum.
func (e ItemValidationProblemCode) Valid() bool {
	switch e {
	case ItemValidationProblemCodeConflictingFields:
		return true
	case ItemValidationProblemCodeDateOverflow:
		return true
	case ItemValidationProblemCodeFutureDate:
		return true
	case ItemValidationProblemCodeInvalidCharacters:
		return true
	case ItemValidationProblemCodeInvalidDate:
		return true
	case ItemValidationProblemCodeInvalidInterval:
		return true
	case ItemValidationProblemCodeInvalidIntervalUnit:
		return true
	case ItemValidationProblemCodeInvalidLength:
		return true
	case ItemValidationProblemCodeInvalidMode:
		return true
	case ItemValidationProblemCodeInvalidReference:
		return true
	case ItemValidationProblemCodeInvalidWorkflowState:
		return true
	case ItemValidationProblemCodeRequiresRecurrence:
		return true
	default:
		return false
	}
}

// Defines values for ItemValidationProblemField.
const (
	ItemValidationProblemFieldAttentionOn           ItemValidationProblemField = "attentionOn"
	ItemValidationProblemFieldHistoricalCompletedOn ItemValidationProblemField = "historicalCompletedOn"
	ItemValidationProblemFieldNotes                 ItemValidationProblemField = "notes"
	ItemValidationProblemFieldRecurrence            ItemValidationProblemField = "recurrence"
	ItemValidationProblemFieldResponsibleUserId     ItemValidationProblemField = "responsibleUserId"
	ItemValidationProblemFieldSubjectId             ItemValidationProblemField = "subjectId"
	ItemValidationProblemFieldTitle                 ItemValidationProblemField = "title"
	ItemValidationProblemFieldWorkflowState         ItemValidationProblemField = "workflowState"
)

// Valid indicates whether the value is a known member of the ItemValidationProblemField enum.
func (e ItemValidationProblemField) Valid() bool {
	switch e {
	case ItemValidationProblemFieldAttentionOn:
		return true
	case ItemValidationProblemFieldHistoricalCompletedOn:
		return true
	case ItemValidationProblemFieldNotes:
		return true
	case ItemValidationProblemFieldRecurrence:
		return true
	case ItemValidationProblemFieldResponsibleUserId:
		return true
	case ItemValidationProblemFieldSubjectId:
		return true
	case ItemValidationProblemFieldTitle:
		return true
	case ItemValidationProblemFieldWorkflowState:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	MemberRoleMember MemberRole = "member"
	MemberRoleOwner  MemberRole = "owner"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleMember:
		return true
	case MemberRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleMember MembershipRole = "member"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for OIDCStartRequestPurpose.
const (
	OIDCPurposeLink  OIDCStartRequestPurpose = "link"
	OIDCPurposeLogin OIDCStartRequestPurpose = "login"
)

// Valid indicates whether the value is a known member of the OIDCStartRequestPurpose enum.
func (e OIDCStartRequestPurpose) Valid() bool {
	switch e {
	case OIDCPurposeLink:
		return true
	case OIDCPurposeLogin:
		return true
	default:
		return false
	}
}

// Defines values for OIDCValidationProblemCode.
const (
	InvalidValue OIDCValidationProblemCode = "invalid_value"
)

// Valid indicates whether the value is a known member of the OIDCValidationProblemCode enum.
func (e OIDCValidationProblemCode) Valid() bool {
	switch e {
	case InvalidValue:
		return true
	default:
		return false
	}
}

// Defines values for OIDCValidationProblemField.
const (
	CurrentPassword OIDCValidationProblemField = "currentPassword"
	Purpose         OIDCValidationProblemField = "purpose"
)

// Valid indicates whether the value is a known member of the OIDCValidationProblemField enum.
func (e OIDCValidationProblemField) Valid() bool {
	switch e {
	case CurrentPassword:
		return true
	case Purpose:
		return true
	default:
		return false
	}
}

// Defines values for QueryProblemParameter.
const (
	QueryProblemParameterArchived QueryProblemParameter = "archived"
	QueryProblemParameterCursor   QueryProblemParameter = "cursor"
	QueryProblemParameterDone     QueryProblemParameter = "done"
	QueryProblemParameterLimit    QueryProblemParameter = "limit"
)

// Valid indicates whether the value is a known member of the QueryProblemParameter enum.
func (e QueryProblemParameter) Valid() bool {
	switch e {
	case QueryProblemParameterArchived:
		return true
	case QueryProblemParameterCursor:
		return true
	case QueryProblemParameterDone:
		return true
	case QueryProblemParameterLimit:
		return true
	default:
		return false
	}
}

// Defines values for RecurrenceIntervalUnit.
const (
	Day   RecurrenceIntervalUnit = "day"
	Month RecurrenceIntervalUnit = "month"
	Week  RecurrenceIntervalUnit = "week"
	Year  RecurrenceIntervalUnit = "year"
)

// Valid indicates whether the value is a known member of the RecurrenceIntervalUnit enum.
func (e RecurrenceIntervalUnit) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	case Week:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Defines values for RecurrenceMode.
const (
	AfterCompletion RecurrenceMode = "after_completion"
	Fixed           RecurrenceMode = "fixed"
)

// Valid indicates whether the value is a known member of the RecurrenceMode enum.
func (e RecurrenceMode) Valid() bool {
	switch e {
	case AfterCompletion:
		return true
	case Fixed:
		return true
	default:
		return false
	}
}

// Defines values for SubjectType.
const (
	Custom  SubjectType = "custom"
	Home    SubjectType = "home"
	Person  SubjectType = "person"
	Pet     SubjectType = "pet"
	Vehicle SubjectType = "vehicle"
)

// Valid indicates whether the value is a known member of the SubjectType enum.
func (e SubjectType) Valid() bool {
	switch e {
	case Custom:
		return true
	case Home:
		return true
	case Person:
		return true
	case Pet:
		return true
	case Vehicle:
		return true
	default:
		return false
	}
}

// Defines values for SubjectValidationProblemCode.
const (
	InvalidCharacters SubjectValidationProblemCode = "invalid_characters"
	InvalidLength     SubjectValidationProblemCode = "invalid_length"
	InvalidType       SubjectValidationProblemCode = "invalid_type"
)

// Valid indicates whether the value is a known member of the SubjectValidationProblemCode enum.
func (e SubjectValidationProblemCode) Valid() bool {
	switch e {
	case InvalidCharacters:
		return true
	case InvalidLength:
		return true
	case InvalidType:
		return true
	default:
		return false
	}
}

// Defines values for SubjectValidationProblemField.
const (
	Name SubjectValidationProblemField = "name"
	Type SubjectValidationProblemField = "type"
)

// Valid indicates whether the value is a known member of the SubjectValidationProblemField enum.
func (e SubjectValidationProblemField) Valid() bool {
	switch e {
	case Name:
		return true
	case Type:
		return true
	default:
		return false
	}
}

// Defines values for UndoCompletionRequestUndone.
const (
	True UndoCompletionRequestUndone = true
)

// Valid indicates whether the value is a known member of the UndoCompletionRequestUndone enum.
func (e UndoCompletionRequestUndone) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ValidationProblemField.
const (
	ValidationProblemFieldHouseholdName ValidationProblemField = "householdName"
	ValidationProblemFieldLogin         ValidationProblemField = "login"
	ValidationProblemFieldPassword      ValidationProblemField = "password"
	ValidationProblemFieldTimezone      ValidationProblemField = "timezone"
)

// Valid indicates whether the value is a known member of the ValidationProblemField enum.
func (e ValidationProblemField) Valid() bool {
	switch e {
	case ValidationProblemFieldHouseholdName:
		return true
	case ValidationProblemFieldLogin:
		return true
	case ValidationProblemFieldPassword:
		return true
	case ValidationProblemFieldTimezone:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowState.
const (
	InProgress WorkflowState = "in_progress"
	Open       WorkflowState = "open"
	Paused     WorkflowState = "paused"
	Waiting    WorkflowState = "waiting"
)

// Valid indicates whether the value is a known member of the WorkflowState enum.
func (e WorkflowState) Valid() bool {
	switch e {
	case InProgress:
		return true
	case Open:
		return true
	case Paused:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// AcceptInvitationNewAccountRequest defines model for AcceptInvitationNewAccountRequest.
type AcceptInvitationNewAccountRequest struct {
	Login string `json:"login"`

	// Password Maximum 512 UTF-8 bytes.
	Password string `json:"password"`
	Token    string `json:"token"`
}

// AcceptInvitationRequest defines model for AcceptInvitationRequest.
type AcceptInvitationRequest struct {
	Token string `json:"token"`
}

// Completion defines model for Completion.
type Completion struct {
	CompletedByUserId string          `json:"completedByUserId"`
	CompletedOn       string          `json:"completedOn"`
	CreatedAt         time.Time       `json:"createdAt"`
	CycleAttentionOn  *string         `json:"cycleAttentionOn"`
	Id                string          `json:"id"`
	ItemId            string          `json:"itemId"`
	NextAttentionOn   *string         `json:"nextAttentionOn"`
	Recurrence        *ItemRecurrence `json:"recurrence"`
	UndoneAt          *time.Time      `json:"undoneAt"`
	UndoneByUserId    *string         `json:"undoneByUserId"`
}

// CompletionList defines model for CompletionList.
type CompletionList struct {
	Items      []Completion `json:"items"`
	NextCursor *string      `json:"nextCursor"`
}

// CompletionProblem defines model for CompletionProblem.
type CompletionProblem struct {
	Code                 *string                 `json:"code,omitempty"`
	Detail               *string                 `json:"detail,omitempty"`
	Field                *CompletionProblemField `json:"field,omitempty"`
	Instance             *string                 `json:"instance,omitempty"`
	Status               int                     `json:"status"`
	Title                string                  `json:"title"`
	Type                 string                  `json:"type"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// CompletionProblemField defines model for CompletionProblem.Field.
type CompletionProblemField string

// CreateCompletionRequest defines model for CreateCompletionRequest.
type CreateCompletionRequest struct {
	// CompletedOn YYYY-MM-DD business date; omitted uses household-local today.
	CompletedOn *string `json:"completedOn,omitempty"`
}

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	// AttentionOn Business date in the household timezone, written YYYY-MM-DD and a real calendar date. Null or omitted means the item needs attention immediately unless historicalCompletedOn supplies the first attention date. Past dates are allowed. Invalid values are rejected with 422.
	AttentionOn **string `json:"attentionOn,omitempty"`

	// HistoricalCompletedOn Optional known historical business date written YYYY-MM-DD and a real calendar date. Requires enabled recurrence, conflicts with non-null attentionOn, cannot be after household-local today, and initializes the first next attention date. Invalid values are rejected with 422.
	HistoricalCompletedOn **string `json:"historicalCompletedOn,omitempty"`

	// Notes Free text stored exactly as given, 1 to 4000 characters. Newline, carriage return, and tab are allowed; other control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected with 422. The empty string is rejected; send null to clear.
	Notes **string `json:"notes,omitempty"`

	// Recurrence Omitted or null means one-off. Recurrence only affects the next completion except explicit historical initialization.
	Recurrence **ItemRecurrence `json:"recurrence,omitempty"`

	// ResponsibleUserId Optional members-list userId of a member of this household. On create, omission or null means unassigned; on PATCH, omission leaves the assignment unchanged and null clears it. A string assigns that member. Malformed, unknown, or foreign-household user IDs return 422 invalid_reference.
	ResponsibleUserId **string `json:"responsibleUserId,omitempty"`

	// SubjectId Identifier of an active subject in the same household; otherwise 422 invalid_reference.
	SubjectId string `json:"subjectId"`

	// Title 1 to 200 characters after trimming leading and trailing whitespace. Control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected with 422.
	Title string `json:"title"`
}

// CreateSubjectRequest defines model for CreateSubjectRequest.
type CreateSubjectRequest struct {
	// Name 1 to 100 characters after trimming leading and trailing whitespace. Control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected. Other values are rejected with 422.
	Name string      `json:"name"`
	Type SubjectType `json:"type"`
}

// EmptyObject defines model for EmptyObject.
type EmptyObject = map[string]interface{}

// Household defines model for Household.
type Household struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`

	// Timezone Named IANA timezone.
	Timezone string `json:"timezone"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	AcceptedAt *time.Time       `json:"acceptedAt"`
	CreatedAt  time.Time        `json:"createdAt"`
	ExpiresAt  time.Time        `json:"expiresAt"`
	Id         string           `json:"id"`
	RevokedAt  *time.Time       `json:"revokedAt"`
	Role       InvitationRole   `json:"role"`
	Status     InvitationStatus `json:"status"`
}

// InvitationRole defines model for Invitation.Role.
type InvitationRole string

// InvitationCreated defines model for InvitationCreated.
type InvitationCreated struct {
	AcceptedAt *time.Time            `json:"acceptedAt"`
	CreatedAt  time.Time             `json:"createdAt"`
	ExpiresAt  time.Time             `json:"expiresAt"`
	Id         string                `json:"id"`
	RevokedAt  *time.Time            `json:"revokedAt"`
	Role       InvitationCreatedRole `json:"role"`
	Status     InvitationStatus      `json:"status"`
	Token      string                `json:"token"`
}

// InvitationCreatedRole defines model for InvitationCreated.Role.
type InvitationCreatedRole string

// InvitationList defines model for InvitationList.
type InvitationList struct {
	Items      []Invitation `json:"items"`
	NextCursor *string      `json:"nextCursor"`
}

// InvitationStatus defines model for InvitationStatus.
type InvitationStatus string

// InvitationValidationProblem defines model for InvitationValidationProblem.
type InvitationValidationProblem struct {
	Code                 InvitationValidationProblemCode  `json:"code"`
	Detail               *string                          `json:"detail,omitempty"`
	Field                InvitationValidationProblemField `json:"field"`
	Instance             *string                          `json:"instance,omitempty"`
	Status               int                              `json:"status"`
	Title                string                           `json:"title"`
	Type                 string                           `json:"type"`
	AdditionalProperties map[string]interface{}           `json:"-"`
}

// InvitationValidationProblemCode defines model for InvitationValidationProblem.Code.
type InvitationValidationProblemCode string

// InvitationValidationProblemField defines model for InvitationValidationProblem.Field.
type InvitationValidationProblemField string

// InvitedAccount defines model for InvitedAccount.
type InvitedAccount struct {
	HouseholdId string             `json:"householdId"`
	Login       string             `json:"login"`
	Role        InvitedAccountRole `json:"role"`
	UserId      string             `json:"userId"`
}

// InvitedAccountRole defines model for InvitedAccount.Role.
type InvitedAccountRole string

// Item defines model for Item.
type Item struct {
	Archived bool `json:"archived"`

	// Attention Derived server-side from attentionOn and today's date in the household timezone; never set by clients. needs_attention when attentionOn is null or not after today, otherwise upcoming.
	Attention ItemAttention `json:"attention"`

	// AttentionOn Current attention date; null means needs attention immediately.
	AttentionOn *string   `json:"attentionOn"`
	CreatedAt   time.Time `json:"createdAt"`

	// Done Read-only lifecycle marker. A one-off item becomes done after completion; recurring items stay active and do not become done.
	Done *bool  `json:"done,omitempty"`
	Id   string `json:"id"`

	// LastCompletedOn Greatest item_version_before among non-undone receipts, or null if none; business date order is not used.
	LastCompletedOn **string `json:"lastCompletedOn,omitempty"`
	Notes           *string  `json:"notes"`

	// Recurrence Recurrence policy; null disables repeat. Policy changes affect the next completion and never change attentionOn.
	Recurrence *ItemRecurrence `json:"recurrence"`

	// ResponsibleUserId Assigned household member userId from the members list; null means unassigned.
	ResponsibleUserId *string       `json:"responsibleUserId"`
	SubjectId         string        `json:"subjectId"`
	Title             string        `json:"title"`
	UpdatedAt         time.Time     `json:"updatedAt"`
	WorkflowState     WorkflowState `json:"workflowState"`
}

// ItemAttention Derived server-side from attentionOn and today's date in the household timezone; never set by clients. needs_attention when attentionOn is null or not after today, otherwise upcoming.
type ItemAttention string

// ItemList defines model for ItemList.
type ItemList struct {
	Items []Item `json:"items"`

	// NextCursor Opaque cursor for the next page; null on the last page.
	NextCursor *string `json:"nextCursor"`
}

// ItemRecurrence Recurrence only affects what happens at the next completion and never changes attentionOn.
type ItemRecurrence struct {
	IntervalUnit  RecurrenceIntervalUnit `json:"intervalUnit"`
	IntervalValue int                    `json:"intervalValue"`

	// Mode fixed = Repeat ON, Fluid OFF: next cycle keeps the planned cadence from the current attention date. after_completion = Repeat ON, Fluid ON: next cycle is counted from the actual completion date. Recurrence only affects what happens at the next completion and never changes attentionOn.
	Mode RecurrenceMode `json:"mode"`
}

// ItemValidationProblem defines model for ItemValidationProblem.
type ItemValidationProblem struct {
	Code                 ItemValidationProblemCode  `json:"code"`
	Detail               *string                    `json:"detail,omitempty"`
	Field                ItemValidationProblemField `json:"field"`
	Instance             *string                    `json:"instance,omitempty"`
	Status               int                        `json:"status"`
	Title                string                     `json:"title"`
	Type                 string                     `json:"type"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// ItemValidationProblemCode defines model for ItemValidationProblem.Code.
type ItemValidationProblemCode string

// ItemValidationProblemField defines model for ItemValidationProblem.Field.
type ItemValidationProblemField string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Member defines model for Member.
type Member struct {
	Login  string     `json:"login"`
	Role   MemberRole `json:"role"`
	UserId string     `json:"userId"`
}

// MemberList defines model for MemberList.
type MemberList struct {
	Items      []Member `json:"items"`
	NextCursor *string  `json:"nextCursor"`
}

// MemberRole defines model for MemberRole.
type MemberRole string

// Membership defines model for Membership.
type Membership struct {
	HouseholdId string         `json:"householdId"`
	Role        MembershipRole `json:"role"`
	UserId      string         `json:"userId"`
}

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// OIDCIdentityStatus defines model for OIDCIdentityStatus.
type OIDCIdentityStatus struct {
	Linked bool `json:"linked"`
}

// OIDCStartRequest currentPassword is required when purpose is link and must be absent when purpose is login; otherwise the server returns 422 OIDCValidationProblem.
type OIDCStartRequest struct {
	CurrentPassword *string                 `json:"currentPassword,omitempty"`
	Purpose         OIDCStartRequestPurpose `json:"purpose"`
}

// OIDCStartRequestPurpose defines model for OIDCStartRequest.Purpose.
type OIDCStartRequestPurpose string

// OIDCStartResponse defines model for OIDCStartResponse.
type OIDCStartResponse struct {
	AuthorizationUrl string `json:"authorizationUrl"`
}

// OIDCStatus displayName is present exactly when enabled is true.
type OIDCStatus struct {
	DisplayName *string `json:"displayName,omitempty"`
	Enabled     bool    `json:"enabled"`
}

// OIDCValidationProblem defines model for OIDCValidationProblem.
type OIDCValidationProblem struct {
	Code   OIDCValidationProblemCode  `json:"code"`
	Field  OIDCValidationProblemField `json:"field"`
	Status int                        `json:"status"`
	Title  string                     `json:"title"`
	Type   string                     `json:"type"`
}

// OIDCValidationProblemCode defines model for OIDCValidationProblem.Code.
type OIDCValidationProblemCode string

// OIDCValidationProblemField defines model for OIDCValidationProblem.Field.
type OIDCValidationProblemField string

// Problem defines model for Problem.
type Problem struct {
	Code                 *string                `json:"code,omitempty"`
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// QueryProblem defines model for QueryProblem.
type QueryProblem struct {
	Code                 *string                `json:"code,omitempty"`
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Parameter            *QueryProblemParameter `json:"parameter,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// QueryProblemParameter defines model for QueryProblem.Parameter.
type QueryProblemParameter string

// RecurrenceIntervalUnit defines model for RecurrenceIntervalUnit.
type RecurrenceIntervalUnit string

// RecurrenceMode fixed = Repeat ON, Fluid OFF: next cycle keeps the planned cadence from the current attention date. after_completion = Repeat ON, Fluid ON: next cycle is counted from the actual completion date. Recurrence only affects what happens at the next completion and never changes attentionOn.
type RecurrenceMode string

// Session defines model for Session.
type Session struct {
	// DefaultHouseholdId Omitted when the account has no default household.
	DefaultHouseholdId *string   `json:"defaultHouseholdId,omitempty"`
	ExpiresAt          time.Time `json:"expiresAt"`
	Login              string    `json:"login"`
	UserId             string    `json:"userId"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	// HouseholdName Trimmed value must be nonempty and contain no control characters.
	HouseholdName string `json:"householdName"`
	Login         string `json:"login"`

	// Password 15–128 Unicode scalar values; maximum 512 UTF-8 bytes
	Password string `json:"password"`

	// Timezone Valid named IANA timezone; UTC accepted; Local and fixed offsets are not accepted.
	Timezone string `json:"timezone"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	Required bool `json:"required"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// Subject defines model for Subject.
type Subject struct {
	Archived  bool        `json:"archived"`
	CreatedAt time.Time   `json:"createdAt"`
	Id        string      `json:"id"`
	Name      string      `json:"name"`
	Type      SubjectType `json:"type"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

// SubjectList defines model for SubjectList.
type SubjectList struct {
	Items []Subject `json:"items"`

	// NextCursor Opaque cursor for the next page; null on the last page.
	NextCursor *string `json:"nextCursor"`
}

// SubjectType defines model for SubjectType.
type SubjectType string

// SubjectValidationProblem defines model for SubjectValidationProblem.
type SubjectValidationProblem struct {
	Code                 SubjectValidationProblemCode  `json:"code"`
	Detail               *string                       `json:"detail,omitempty"`
	Field                SubjectValidationProblemField `json:"field"`
	Instance             *string                       `json:"instance,omitempty"`
	Status               int                           `json:"status"`
	Title                string                        `json:"title"`
	Type                 string                        `json:"type"`
	AdditionalProperties map[string]interface{}        `json:"-"`
}

// SubjectValidationProblemCode defines model for SubjectValidationProblem.Code.
type SubjectValidationProblemCode string

// SubjectValidationProblemField defines model for SubjectValidationProblem.Field.
type SubjectValidationProblemField string

// UndoCompletionRequest defines model for UndoCompletionRequest.
type UndoCompletionRequest struct {
	Undone UndoCompletionRequestUndone `json:"undone"`
}

// UndoCompletionRequestUndone defines model for UndoCompletionRequest.Undone.
type UndoCompletionRequestUndone bool

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Archived *bool `json:"archived,omitempty"`

	// AttentionOn Business date in the household timezone, written YYYY-MM-DD and a real calendar date. Omitted leaves the current date unchanged; null clears it and makes the item need attention immediately. Past dates are allowed. Invalid values are rejected with 422.
	AttentionOn **string `json:"attentionOn,omitempty"`

	// Notes Free text stored exactly as given, 1 to 4000 characters. Newline, carriage return, and tab are allowed; other control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected with 422. The empty string is rejected; send null to clear. Null clears the notes.
	Notes **string `json:"notes,omitempty"`

	// Recurrence Object replaces the whole recurrence policy; null disables repeat; omitted leaves it unchanged. Changes affect only the next completion and never change attentionOn.
	Recurrence **ItemRecurrence `json:"recurrence,omitempty"`

	// ResponsibleUserId Optional members-list userId of a member of this household. On create, omission or null means unassigned; on PATCH, omission leaves the assignment unchanged and null clears it. A string assigns that member. Malformed, unknown, or foreign-household user IDs return 422 invalid_reference.
	ResponsibleUserId **string `json:"responsibleUserId,omitempty"`

	// SubjectId Identifier of an active subject in the same household; otherwise 422 invalid_reference.
	SubjectId *string `json:"subjectId,omitempty"`

	// Title 1 to 200 characters after trimming leading and trailing whitespace. Control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected with 422.
	Title         *string        `json:"title,omitempty"`
	WorkflowState *WorkflowState `json:"workflowState,omitempty"`
}

// UpdateSubjectRequest defines model for UpdateSubjectRequest.
type UpdateSubjectRequest struct {
	Archived *bool `json:"archived,omitempty"`

	// Name 1 to 100 characters after trimming leading and trailing whitespace. Control, format (zero-width and bidirectional), and line or paragraph separator characters are rejected. Other values are rejected with 422.
	Name *string      `json:"name,omitempty"`
	Type *SubjectType `json:"type,omitempty"`
}

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	Code                 string                 `json:"code"`
	Detail               *string                `json:"detail,omitempty"`
	Field                ValidationProblemField `json:"field"`
	Instance             *string                `json:"instance,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ValidationProblemField defines model for ValidationProblem.Field.
type ValidationProblemField string

// WorkflowState defines model for WorkflowState.
type WorkflowState string

// Archived defines model for Archived.
type Archived = bool

// Cursor defines model for Cursor.
type Cursor = string

// Done defines model for Done.
type Done = bool

// HouseholdId defines model for HouseholdId.
type HouseholdId = string

// InvitationId defines model for InvitationId.
type InvitationId = string

// ItemId defines model for ItemId.
type ItemId = string

// Limit defines model for Limit.
type Limit = int

// RequestId defines model for RequestId.
type RequestId = string

// SubjectId defines model for SubjectId.
type SubjectId = string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// setupTokenContextKey is the context key for SetupToken security scheme
type setupTokenContextKey string

// AcceptInvitationWithNewAccountParams defines parameters for AcceptInvitationWithNewAccount.
type AcceptInvitationWithNewAccountParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetOidcStatusParams defines parameters for GetOidcStatus.
type GetOidcStatusParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CompleteOidcCallbackParams defines parameters for CompleteOidcCallback.
type CompleteOidcCallbackParams struct {
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	State            *string `form:"state,omitempty" json:"state,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
	Iss              *string `form:"iss,omitempty" json:"iss,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetOidcIdentityParams defines parameters for GetOidcIdentity.
type GetOidcIdentityParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// StartOidcParams defines parameters for StartOidc.
type StartOidcParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
	Origin     string     `json:"Origin"`
}

// GetInitialSetupParams defines parameters for GetInitialSetup.
type GetInitialSetupParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateInitialOwnerParams defines parameters for CreateInitialOwner.
type CreateInitialOwnerParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match the configured canonical public origin.
	Origin string `json:"Origin"`
}

// GetHouseholdParams defines parameters for GetHousehold.
type GetHouseholdParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ListInvitationsParams defines parameters for ListInvitations.
type ListInvitationsParams struct {
	// Limit Maximum number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor copied from a previous nextCursor. Do not construct or parse it.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateInvitationParams defines parameters for CreateInvitation.
type CreateInvitationParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID     *RequestId `json:"X-Request-ID,omitempty"`
	IdempotencyKey string     `json:"Idempotency-Key"`
}

// RevokeInvitationParams defines parameters for RevokeInvitation.
type RevokeInvitationParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Limit Maximum number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor copied from a previous nextCursor. Do not construct or parse it.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Archived false (default) lists active items; true lists archived items only, independently of done status.
	Archived *Archived `form:"archived,omitempty" json:"archived,omitempty"`

	// Done false (default) lists unfinished items; true lists completed one-off items.
	Done *Done `form:"done,omitempty" json:"done,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateItemParams defines parameters for CreateItem.
type CreateItemParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetItemParams defines parameters for GetItem.
type GetItemParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// UpdateItemParams defines parameters for UpdateItem.
type UpdateItemParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// IfMatch Single strong entity tag of the version being replaced. The wildcard *, weak tags, and lists are rejected with 412.
	IfMatch string `json:"If-Match"`
}

// ListItemCompletionsParams defines parameters for ListItemCompletions.
type ListItemCompletionsParams struct {
	// Limit Maximum number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor copied from a previous nextCursor. Do not construct or parse it.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateItemCompletionParams defines parameters for CreateItemCompletion.
type CreateItemCompletionParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// IfMatch Single strong ETag for the current item version. Missing returns 428; malformed, weak, wildcard, list, or stale values return 412.
	IfMatch string `json:"If-Match"`

	// IdempotencyKey Required, case-sensitive, 1–128 printable ASCII bytes (0x21–0x7E); no normalization. Missing returns 400 idempotency_key_required; invalid or repeated headers return 400 invalid_idempotency_key.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// UndoItemCompletionParams defines parameters for UndoItemCompletion.
type UndoItemCompletionParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// IfMatch Exactly one syntactically valid strong item ETag is required on every request. Missing returns 428; malformed, weak, wildcard, or list returns 412. For an already-undone replay only the stored-version comparison is skipped.
	IfMatch string `json:"If-Match"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	// Limit Maximum number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor copied from a previous nextCursor. Do not construct or parse it.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ListSubjectsParams defines parameters for ListSubjects.
type ListSubjectsParams struct {
	// Limit Maximum number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor copied from a previous nextCursor. Do not construct or parse it.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Archived false (default) lists active items; true lists archived items only, independently of done status.
	Archived *Archived `form:"archived,omitempty" json:"archived,omitempty"`

	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateSubjectParams defines parameters for CreateSubject.
type CreateSubjectParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetSubjectParams defines parameters for GetSubject.
type GetSubjectParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// UpdateSubjectParams defines parameters for UpdateSubject.
type UpdateSubjectParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// IfMatch Single strong entity tag of the version being replaced. The wildcard *, weak tags, and lists are rejected with 412.
	IfMatch string `json:"If-Match"`
}

// AcceptInvitationParams defines parameters for AcceptInvitation.
type AcceptInvitationParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// DeleteSessionParams defines parameters for DeleteSession.
type DeleteSessionParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match the configured canonical public origin.
	Origin string `json:"Origin"`
}

// GetSessionParams defines parameters for GetSession.
type GetSessionParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// CreateSessionParams defines parameters for CreateSession.
type CreateSessionParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match the configured canonical public origin.
	Origin string `json:"Origin"`
}

// GetLivenessParams defines parameters for GetLiveness.
type GetLivenessParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetReadinessParams defines parameters for GetReadiness.
type GetReadinessParams struct {
	// XRequestID Optional caller-supplied correlation ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// AcceptInvitationWithNewAccountJSONRequestBody defines body for AcceptInvitationWithNewAccount for application/json ContentType.
type AcceptInvitationWithNewAccountJSONRequestBody = AcceptInvitationNewAccountRequest

// StartOidcJSONRequestBody defines body for StartOidc for application/json ContentType.
type StartOidcJSONRequestBody = OIDCStartRequest

// CreateInitialOwnerJSONRequestBody defines body for CreateInitialOwner for application/json ContentType.
type CreateInitialOwnerJSONRequestBody = SetupRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = EmptyObject

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// CreateItemCompletionJSONRequestBody defines body for CreateItemCompletion for application/json ContentType.
type CreateItemCompletionJSONRequestBody = CreateCompletionRequest

// UndoItemCompletionJSONRequestBody defines body for UndoItemCompletion for application/json ContentType.
type UndoItemCompletionJSONRequestBody = UndoCompletionRequest

// CreateSubjectJSONRequestBody defines body for CreateSubject for application/json ContentType.
type CreateSubjectJSONRequestBody = CreateSubjectRequest

// UpdateSubjectJSONRequestBody defines body for UpdateSubject for application/json ContentType.
type UpdateSubjectJSONRequestBody = UpdateSubjectRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = AcceptInvitationRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = LoginRequest

// Getter for additional properties for CompletionProblem. Returns the specified
// element and whether it was found
func (a CompletionProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CompletionProblem
func (a *CompletionProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CompletionProblem to handle AdditionalProperties
func (a *CompletionProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CompletionProblem to handle AdditionalProperties
func (a CompletionProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Field != nil {
		object["field"], err = json.Marshal(a.Field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InvitationValidationProblem. Returns the specified
// element and whether it was found
func (a InvitationValidationProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InvitationValidationProblem
func (a *InvitationValidationProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InvitationValidationProblem to handle AdditionalProperties
func (a *InvitationValidationProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InvitationValidationProblem to handle AdditionalProperties
func (a InvitationValidationProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ItemValidationProblem. Returns the specified
// element and whether it was found
func (a ItemValidationProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ItemValidationProblem
func (a *ItemValidationProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ItemValidationProblem to handle AdditionalProperties
func (a *ItemValidationProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ItemValidationProblem to handle AdditionalProperties
func (a ItemValidationProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for QueryProblem. Returns the specified
// element and whether it was found
func (a QueryProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for QueryProblem
func (a *QueryProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for QueryProblem to handle AdditionalProperties
func (a *QueryProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["parameter"]; found {
		err = json.Unmarshal(raw, &a.Parameter)
		if err != nil {
			return fmt.Errorf("error reading 'parameter': %w", err)
		}
		delete(object, "parameter")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for QueryProblem to handle AdditionalProperties
func (a QueryProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Parameter != nil {
		object["parameter"], err = json.Marshal(a.Parameter)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parameter': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SubjectValidationProblem. Returns the specified
// element and whether it was found
func (a SubjectValidationProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SubjectValidationProblem
func (a *SubjectValidationProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SubjectValidationProblem to handle AdditionalProperties
func (a *SubjectValidationProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SubjectValidationProblem to handle AdditionalProperties
func (a SubjectValidationProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ValidationProblem. Returns the specified
// element and whether it was found
func (a ValidationProblem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ValidationProblem
func (a *ValidationProblem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ValidationProblem to handle AdditionalProperties
func (a *ValidationProblem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ValidationProblem to handle AdditionalProperties
func (a ValidationProblem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
