// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMemberHousehold = `-- name: FindMemberHousehold :one
SELECT h.id::text AS id, h.name, h.timezone, h.created_at, h.version
FROM households h
JOIN household_memberships m ON m.household_id = h.id
WHERE h.id = $1 AND m.user_id = $2
`

type FindMemberHouseholdParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type FindMemberHouseholdRow struct {
	ID        string
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	Version   int64
}

func (q *Queries) FindMemberHousehold(ctx context.Context, arg FindMemberHouseholdParams) (FindMemberHouseholdRow, error) {
	row := q.db.QueryRow(ctx, findMemberHousehold, arg.ID, arg.UserID)
	var i FindMemberHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
