// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInvitedMember = `-- name: AddInvitedMember :exec
INSERT INTO household_memberships(user_id, household_id, role) VALUES($1, $2, 'member')
`

type AddInvitedMemberParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) AddInvitedMember(ctx context.Context, arg AddInvitedMemberParams) error {
	_, err := q.db.Exec(ctx, addInvitedMember, arg.UserID, arg.HouseholdID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT role FROM household_memberships WHERE user_id=$1 AND household_id=$2
`

type GetMembershipParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.HouseholdID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getMembershipForInvitation = `-- name: GetMembershipForInvitation :one
SELECT role FROM household_memberships WHERE user_id=$1 AND household_id=$2
`

type GetMembershipForInvitationParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) GetMembershipForInvitation(ctx context.Context, arg GetMembershipForInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipForInvitation, arg.UserID, arg.HouseholdID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const hasMembershipElsewhere = `-- name: HasMembershipElsewhere :one
SELECT EXISTS(SELECT 1 FROM household_memberships WHERE user_id=$1 AND household_id<>$2)
`

type HasMembershipElsewhereParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) HasMembershipElsewhere(ctx context.Context, arg HasMembershipElsewhereParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembershipElsewhere, arg.UserID, arg.HouseholdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMembers = `-- name: ListMembers :many
SELECT user_id::text AS user_id, role
FROM household_memberships
WHERE household_id=$1 AND ($2::uuid IS NULL OR user_id > $2::uuid)
ORDER BY user_id LIMIT $3
`

type ListMembersParams struct {
	HouseholdID pgtype.UUID
	Column2     pgtype.UUID
	Limit       int32
}

type ListMembersRow struct {
	UserID string
	Role   string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.HouseholdID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
