// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	AddOwner(ctx context.Context, arg AddOwnerParams) error
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (string, error)
	FindMemberHousehold(ctx context.Context, arg FindMemberHouseholdParams) (FindMemberHouseholdRow, error)
}

var _ Querier = (*Queries)(nil)
