// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setup.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOwner = `-- name: AddOwner :exec
INSERT INTO household_memberships (user_id, household_id, role) VALUES ($1, $2, 'owner')
`

type AddOwnerParams struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) error {
	_, err := q.db.Exec(ctx, addOwner, arg.UserID, arg.HouseholdID)
	return err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, timezone) VALUES ($1, $2) RETURNING id::text
`

type CreateHouseholdParams struct {
	Name     string
	Timezone string
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (string, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.Timezone)
	var id string
	err := row.Scan(&id)
	return id, err
}
