// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: completion.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompletionByKey = `-- name: GetCompletionByKey :one
SELECT id::text AS id, household_id::text AS household_id, item_id::text AS item_id, completed_on, completed_by_user_id::text AS completed_by_user_id, cycle_attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, prior_workflow_state, next_attention_on, item_version_before, idempotency_key, request_fingerprint, created_at FROM item_completions WHERE household_id=$1 AND item_id=$2 AND idempotency_key=$3
`

type GetCompletionByKeyParams struct {
	HouseholdID    pgtype.UUID
	ItemID         pgtype.UUID
	IdempotencyKey string
}

type GetCompletionByKeyRow struct {
	ID                      string
	HouseholdID             string
	ItemID                  string
	CompletedOn             pgtype.Date
	CompletedByUserID       string
	CycleAttentionOn        pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	PriorWorkflowState      string
	NextAttentionOn         pgtype.Date
	ItemVersionBefore       int64
	IdempotencyKey          string
	RequestFingerprint      []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) GetCompletionByKey(ctx context.Context, arg GetCompletionByKeyParams) (GetCompletionByKeyRow, error) {
	row := q.db.QueryRow(ctx, getCompletionByKey, arg.HouseholdID, arg.ItemID, arg.IdempotencyKey)
	var i GetCompletionByKeyRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ItemID,
		&i.CompletedOn,
		&i.CompletedByUserID,
		&i.CycleAttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.PriorWorkflowState,
		&i.NextAttentionOn,
		&i.ItemVersionBefore,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompletion = `-- name: InsertCompletion :one
INSERT INTO item_completions (household_id,item_id,completed_on,completed_by_user_id,cycle_attention_on,recurrence_interval_value,recurrence_interval_unit,recurrence_mode,prior_workflow_state,next_attention_on,item_version_before,idempotency_key,request_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id::text AS id, household_id::text AS household_id, item_id::text AS item_id, completed_on, completed_by_user_id::text AS completed_by_user_id, cycle_attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, prior_workflow_state, next_attention_on, item_version_before, idempotency_key, request_fingerprint, created_at
`

type InsertCompletionParams struct {
	HouseholdID             pgtype.UUID
	ItemID                  pgtype.UUID
	CompletedOn             pgtype.Date
	CompletedByUserID       pgtype.UUID
	CycleAttentionOn        pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	PriorWorkflowState      string
	NextAttentionOn         pgtype.Date
	ItemVersionBefore       int64
	IdempotencyKey          string
	RequestFingerprint      []byte
}

type InsertCompletionRow struct {
	ID                      string
	HouseholdID             string
	ItemID                  string
	CompletedOn             pgtype.Date
	CompletedByUserID       string
	CycleAttentionOn        pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	PriorWorkflowState      string
	NextAttentionOn         pgtype.Date
	ItemVersionBefore       int64
	IdempotencyKey          string
	RequestFingerprint      []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) InsertCompletion(ctx context.Context, arg InsertCompletionParams) (InsertCompletionRow, error) {
	row := q.db.QueryRow(ctx, insertCompletion,
		arg.HouseholdID,
		arg.ItemID,
		arg.CompletedOn,
		arg.CompletedByUserID,
		arg.CycleAttentionOn,
		arg.RecurrenceIntervalValue,
		arg.RecurrenceIntervalUnit,
		arg.RecurrenceMode,
		arg.PriorWorkflowState,
		arg.NextAttentionOn,
		arg.ItemVersionBefore,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
	)
	var i InsertCompletionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ItemID,
		&i.CompletedOn,
		&i.CompletedByUserID,
		&i.CycleAttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.PriorWorkflowState,
		&i.NextAttentionOn,
		&i.ItemVersionBefore,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const listCompletions = `-- name: ListCompletions :many
SELECT id::text AS id, household_id::text AS household_id, item_id::text AS item_id, completed_on, completed_by_user_id::text AS completed_by_user_id, cycle_attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, prior_workflow_state, next_attention_on, item_version_before, idempotency_key, request_fingerprint, created_at FROM item_completions WHERE household_id=$1 AND item_id=$2 AND id>$3 ORDER BY id ASC LIMIT $4
`

type ListCompletionsParams struct {
	HouseholdID pgtype.UUID
	ItemID      pgtype.UUID
	ID          pgtype.UUID
	Limit       int32
}

type ListCompletionsRow struct {
	ID                      string
	HouseholdID             string
	ItemID                  string
	CompletedOn             pgtype.Date
	CompletedByUserID       string
	CycleAttentionOn        pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	PriorWorkflowState      string
	NextAttentionOn         pgtype.Date
	ItemVersionBefore       int64
	IdempotencyKey          string
	RequestFingerprint      []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) ListCompletions(ctx context.Context, arg ListCompletionsParams) ([]ListCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listCompletions,
		arg.HouseholdID,
		arg.ItemID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletionsRow{}
	for rows.Next() {
		var i ListCompletionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ItemID,
			&i.CompletedOn,
			&i.CompletedByUserID,
			&i.CycleAttentionOn,
			&i.RecurrenceIntervalValue,
			&i.RecurrenceIntervalUnit,
			&i.RecurrenceMode,
			&i.PriorWorkflowState,
			&i.NextAttentionOn,
			&i.ItemVersionBefore,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItemForCompletion = `-- name: LockItemForCompletion :one
SELECT id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, (SELECT completed_on FROM item_completions c WHERE c.household_id = items.household_id AND c.item_id = items.id ORDER BY c.item_version_before DESC LIMIT 1) AS last_completed_on, created_at, updated_at, version FROM items WHERE items.household_id=$1 AND items.id=$2 FOR UPDATE
`

type LockItemForCompletionParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type LockItemForCompletionRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) LockItemForCompletion(ctx context.Context, arg LockItemForCompletionParams) (LockItemForCompletionRow, error) {
	row := q.db.QueryRow(ctx, lockItemForCompletion, arg.HouseholdID, arg.ID)
	var i LockItemForCompletionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.WorkflowState,
		&i.Archived,
		&i.Done,
		&i.LastCompletedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateItemForCompletion = `-- name: UpdateItemForCompletion :exec
UPDATE items SET attention_on=$3, workflow_state=$4, done=$5, version=version+1, updated_at=now() WHERE household_id=$1 AND id=$2
`

type UpdateItemForCompletionParams struct {
	HouseholdID   pgtype.UUID
	ID            pgtype.UUID
	AttentionOn   pgtype.Date
	WorkflowState string
	Done          bool
}

func (q *Queries) UpdateItemForCompletion(ctx context.Context, arg UpdateItemForCompletionParams) error {
	_, err := q.db.Exec(ctx, updateItemForCompletion,
		arg.HouseholdID,
		arg.ID,
		arg.AttentionOn,
		arg.WorkflowState,
		arg.Done,
	)
	return err
}
