// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (household_id, subject_id, title, notes, attention_on)
VALUES ($1, $2, $3, $4::text, $5::date)
RETURNING id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, title, notes, attention_on, workflow_state, archived, created_at, updated_at, version
`

type CreateItemParams struct {
	HouseholdID pgtype.UUID
	SubjectID   pgtype.UUID
	Title       string
	Notes       pgtype.Text
	AttentionOn pgtype.Date
}

type CreateItemRow struct {
	ID            string
	HouseholdID   string
	SubjectID     string
	Title         string
	Notes         pgtype.Text
	AttentionOn   pgtype.Date
	WorkflowState string
	Archived      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.HouseholdID,
		arg.SubjectID,
		arg.Title,
		arg.Notes,
		arg.AttentionOn,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.WorkflowState,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, title, notes, attention_on, workflow_state, archived, created_at, updated_at, version
FROM items
WHERE household_id = $1 AND id = $2
`

type GetItemParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetItemRow struct {
	ID            string
	HouseholdID   string
	SubjectID     string
	Title         string
	Notes         pgtype.Text
	AttentionOn   pgtype.Date
	WorkflowState string
	Archived      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, arg.HouseholdID, arg.ID)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.WorkflowState,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, title, notes, attention_on, workflow_state, archived, created_at, updated_at, version
FROM items
WHERE household_id = $1 AND archived = $2 AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListItemsParams struct {
	HouseholdID pgtype.UUID
	Archived    bool
	AfterID     pgtype.UUID
	RowLimit    int32
}

type ListItemsRow struct {
	ID            string
	HouseholdID   string
	SubjectID     string
	Title         string
	Notes         pgtype.Text
	AttentionOn   pgtype.Date
	WorkflowState string
	Archived      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.HouseholdID,
		arg.Archived,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.SubjectID,
			&i.Title,
			&i.Notes,
			&i.AttentionOn,
			&i.WorkflowState,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET title = COALESCE($1::text, title),
    subject_id = COALESCE($2::uuid, subject_id),
    notes = CASE WHEN $3::boolean THEN $4::text ELSE notes END,
    attention_on = CASE WHEN $5::boolean THEN $6::date ELSE attention_on END,
    workflow_state = COALESCE($7::text, workflow_state),
    archived = COALESCE($8::boolean, archived),
    version = version + 1,
    updated_at = now()
WHERE household_id = $9 AND id = $10 AND version = $11
RETURNING id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, title, notes, attention_on, workflow_state, archived, created_at, updated_at, version
`

type UpdateItemParams struct {
	Title           pgtype.Text
	SubjectID       pgtype.UUID
	SetNotes        bool
	Notes           pgtype.Text
	SetAttentionOn  bool
	AttentionOn     pgtype.Date
	WorkflowState   pgtype.Text
	Archived        pgtype.Bool
	HouseholdID     pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int64
}

type UpdateItemRow struct {
	ID            string
	HouseholdID   string
	SubjectID     string
	Title         string
	Notes         pgtype.Text
	AttentionOn   pgtype.Date
	WorkflowState string
	Archived      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Title,
		arg.SubjectID,
		arg.SetNotes,
		arg.Notes,
		arg.SetAttentionOn,
		arg.AttentionOn,
		arg.WorkflowState,
		arg.Archived,
		arg.HouseholdID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.WorkflowState,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
