// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (household_id, subject_id, responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode)
VALUES ($1, $2, $3::uuid, $4, $5::text, $6::date, $7::integer, $8::text, $9::text)
RETURNING id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, responsible_user_id AS responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, (SELECT completed_on FROM item_completions c WHERE c.household_id = items.household_id AND c.item_id = items.id AND c.undone_at IS NULL ORDER BY c.item_version_before DESC LIMIT 1) AS last_completed_on, created_at, updated_at, version
`

type CreateItemParams struct {
	HouseholdID             pgtype.UUID
	SubjectID               pgtype.UUID
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
}

type CreateItemRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.HouseholdID,
		arg.SubjectID,
		arg.ResponsibleUserID,
		arg.Title,
		arg.Notes,
		arg.AttentionOn,
		arg.RecurrenceIntervalValue,
		arg.RecurrenceIntervalUnit,
		arg.RecurrenceMode,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.ResponsibleUserID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.WorkflowState,
		&i.Archived,
		&i.Done,
		&i.LastCompletedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, responsible_user_id AS responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, (SELECT completed_on FROM item_completions c WHERE c.household_id = items.household_id AND c.item_id = items.id AND c.undone_at IS NULL ORDER BY c.item_version_before DESC LIMIT 1) AS last_completed_on, created_at, updated_at, version
FROM items
WHERE items.household_id = $1 AND items.id = $2
`

type GetItemParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetItemRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, arg.HouseholdID, arg.ID)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.ResponsibleUserID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.WorkflowState,
		&i.Archived,
		&i.Done,
		&i.LastCompletedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertInitializedItem = `-- name: InsertInitializedItem :one
INSERT INTO items (household_id, subject_id, responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, version)
VALUES ($1, $2, $3::uuid, $4, $5::text, NULL, $6::integer, $7::text, $8::text, 1)
RETURNING id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, responsible_user_id AS responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, NULL::date AS last_completed_on, created_at, updated_at, version
`

type InsertInitializedItemParams struct {
	HouseholdID             pgtype.UUID
	SubjectID               pgtype.UUID
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
}

type InsertInitializedItemRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) InsertInitializedItem(ctx context.Context, arg InsertInitializedItemParams) (InsertInitializedItemRow, error) {
	row := q.db.QueryRow(ctx, insertInitializedItem,
		arg.HouseholdID,
		arg.SubjectID,
		arg.ResponsibleUserID,
		arg.Title,
		arg.Notes,
		arg.RecurrenceIntervalValue,
		arg.RecurrenceIntervalUnit,
		arg.RecurrenceMode,
	)
	var i InsertInitializedItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.ResponsibleUserID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.WorkflowState,
		&i.Archived,
		&i.Done,
		&i.LastCompletedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, responsible_user_id AS responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, (SELECT completed_on FROM item_completions c WHERE c.household_id = items.household_id AND c.item_id = items.id AND c.undone_at IS NULL ORDER BY c.item_version_before DESC LIMIT 1) AS last_completed_on, created_at, updated_at, version
FROM items
WHERE items.household_id = $1 AND archived = $2 AND done = $3 AND items.id > $4
ORDER BY id ASC
LIMIT $5
`

type ListItemsParams struct {
	HouseholdID pgtype.UUID
	Archived    bool
	Done        bool
	AfterID     pgtype.UUID
	RowLimit    int32
}

type ListItemsRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.HouseholdID,
		arg.Archived,
		arg.Done,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.SubjectID,
			&i.ResponsibleUserID,
			&i.Title,
			&i.Notes,
			&i.AttentionOn,
			&i.RecurrenceIntervalValue,
			&i.RecurrenceIntervalUnit,
			&i.RecurrenceMode,
			&i.WorkflowState,
			&i.Archived,
			&i.Done,
			&i.LastCompletedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET title = COALESCE($1::text, title),
    subject_id = COALESCE($2::uuid, subject_id),
    responsible_user_id = CASE WHEN $3::boolean THEN $4::uuid ELSE responsible_user_id END,
    notes = CASE WHEN $5::boolean THEN $6::text ELSE notes END,
    attention_on = CASE WHEN $7::boolean THEN $8::date ELSE attention_on END,
    recurrence_interval_value = CASE WHEN $9::boolean THEN $10::integer ELSE recurrence_interval_value END,
    recurrence_interval_unit = CASE WHEN $9::boolean THEN $11::text ELSE recurrence_interval_unit END,
    recurrence_mode = CASE WHEN $9::boolean THEN $12::text ELSE recurrence_mode END,
    workflow_state = COALESCE($13::text, workflow_state),
    archived = COALESCE($14::boolean, archived),
    version = version + 1,
    updated_at = now()
WHERE items.household_id = $15 AND items.id = $16 AND version = $17
RETURNING id::text AS id, household_id::text AS household_id, subject_id::text AS subject_id, responsible_user_id AS responsible_user_id, title, notes, attention_on, recurrence_interval_value, recurrence_interval_unit, recurrence_mode, workflow_state, archived, done, (SELECT completed_on FROM item_completions c WHERE c.household_id = items.household_id AND c.item_id = items.id AND c.undone_at IS NULL ORDER BY c.item_version_before DESC LIMIT 1) AS last_completed_on, created_at, updated_at, version
`

type UpdateItemParams struct {
	Title                   pgtype.Text
	SubjectID               pgtype.UUID
	SetResponsibleUserID    bool
	ResponsibleUserID       pgtype.UUID
	SetNotes                bool
	Notes                   pgtype.Text
	SetAttentionOn          bool
	AttentionOn             pgtype.Date
	SetRecurrence           bool
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           pgtype.Text
	Archived                pgtype.Bool
	HouseholdID             pgtype.UUID
	ID                      pgtype.UUID
	ExpectedVersion         int64
}

type UpdateItemRow struct {
	ID                      string
	HouseholdID             string
	SubjectID               string
	ResponsibleUserID       pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	WorkflowState           string
	Archived                bool
	Done                    bool
	LastCompletedOn         pgtype.Date
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Title,
		arg.SubjectID,
		arg.SetResponsibleUserID,
		arg.ResponsibleUserID,
		arg.SetNotes,
		arg.Notes,
		arg.SetAttentionOn,
		arg.AttentionOn,
		arg.SetRecurrence,
		arg.RecurrenceIntervalValue,
		arg.RecurrenceIntervalUnit,
		arg.RecurrenceMode,
		arg.WorkflowState,
		arg.Archived,
		arg.HouseholdID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.SubjectID,
		&i.ResponsibleUserID,
		&i.Title,
		&i.Notes,
		&i.AttentionOn,
		&i.RecurrenceIntervalValue,
		&i.RecurrenceIntervalUnit,
		&i.RecurrenceMode,
		&i.WorkflowState,
		&i.Archived,
		&i.Done,
		&i.LastCompletedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
