// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID        pgtype.UUID
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type HouseholdMembership struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	Role        string
}

type InstallationState struct {
	Singleton     bool
	SetupRequired bool
}

type Item struct {
	ID            pgtype.UUID
	HouseholdID   pgtype.UUID
	SubjectID     pgtype.UUID
	Title         string
	Notes         pgtype.Text
	AttentionOn   pgtype.Date
	WorkflowState string
	Archived      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
}

type LocalCredential struct {
	UserID       pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Subject struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type UserAccount struct {
	ID                 pgtype.UUID
	Login              string
	DefaultHouseholdID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type UserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
