// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID        pgtype.UUID
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type HouseholdInvitation struct {
	ID              pgtype.UUID
	HouseholdID     pgtype.UUID
	CreatedByUserID pgtype.UUID
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type HouseholdMembership struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	Role        string
}

type InstallationState struct {
	Singleton     bool
	SetupRequired bool
}

type Item struct {
	ID                      pgtype.UUID
	HouseholdID             pgtype.UUID
	SubjectID               pgtype.UUID
	Title                   string
	Notes                   pgtype.Text
	AttentionOn             pgtype.Date
	WorkflowState           string
	Archived                bool
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	Done                    bool
	ResponsibleUserID       pgtype.UUID
}

type ItemCompletion struct {
	ID                      pgtype.UUID
	HouseholdID             pgtype.UUID
	ItemID                  pgtype.UUID
	CompletedOn             pgtype.Date
	CompletedByUserID       pgtype.UUID
	CycleAttentionOn        pgtype.Date
	RecurrenceIntervalValue pgtype.Int4
	RecurrenceIntervalUnit  pgtype.Text
	RecurrenceMode          pgtype.Text
	PriorWorkflowState      string
	NextAttentionOn         pgtype.Date
	ItemVersionBefore       int64
	IdempotencyKey          string
	RequestFingerprint      []byte
	CreatedAt               pgtype.Timestamptz
	UndoneAt                pgtype.Timestamptz
	UndoneByUserID          pgtype.UUID
}

type LocalCredential struct {
	UserID       pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Subject struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type UserAccount struct {
	ID                 pgtype.UUID
	Login              string
	DefaultHouseholdID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type UserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
