// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error)
	GetItem(ctx context.Context, arg GetItemParams) (GetItemRow, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error)
}

var _ Querier = (*Queries)(nil)
