// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE household_invitations SET accepted_at=$2 WHERE id=$1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $2
`

type AcceptInvitationParams struct {
	ID         pgtype.UUID
	AcceptedAt pgtype.Timestamptz
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.ID, arg.AcceptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO household_invitations(household_id, created_by_user_id, creation_key, token_hash, created_at, expires_at)
VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (household_id, created_by_user_id, creation_key) DO NOTHING
RETURNING id::text, household_id::text, created_by_user_id::text, creation_key, token_hash, created_at, expires_at, accepted_at, revoked_at
`

type CreateInvitationParams struct {
	HouseholdID     pgtype.UUID
	CreatedByUserID pgtype.UUID
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type CreateInvitationRow struct {
	ID              string
	HouseholdID     string
	CreatedByUserID string
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.HouseholdID,
		arg.CreatedByUserID,
		arg.CreationKey,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedByUserID,
		&i.CreationKey,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findInvitationByCreationKey = `-- name: FindInvitationByCreationKey :one
SELECT id::text, household_id::text, created_by_user_id::text, creation_key, token_hash, created_at, expires_at, accepted_at, revoked_at
FROM household_invitations WHERE household_id=$1 AND created_by_user_id=$2 AND creation_key=$3
`

type FindInvitationByCreationKeyParams struct {
	HouseholdID     pgtype.UUID
	CreatedByUserID pgtype.UUID
	CreationKey     string
}

type FindInvitationByCreationKeyRow struct {
	ID              string
	HouseholdID     string
	CreatedByUserID string
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) FindInvitationByCreationKey(ctx context.Context, arg FindInvitationByCreationKeyParams) (FindInvitationByCreationKeyRow, error) {
	row := q.db.QueryRow(ctx, findInvitationByCreationKey, arg.HouseholdID, arg.CreatedByUserID, arg.CreationKey)
	var i FindInvitationByCreationKeyRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedByUserID,
		&i.CreationKey,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findInvitationByToken = `-- name: FindInvitationByToken :one
SELECT id::text, household_id::text, created_by_user_id::text, creation_key, token_hash, created_at, expires_at, accepted_at, revoked_at
FROM household_invitations WHERE token_hash=$1
`

type FindInvitationByTokenRow struct {
	ID              string
	HouseholdID     string
	CreatedByUserID string
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) FindInvitationByToken(ctx context.Context, tokenHash []byte) (FindInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, findInvitationByToken, tokenHash)
	var i FindInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedByUserID,
		&i.CreationKey,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findInvitationByTokenForUpdate = `-- name: FindInvitationByTokenForUpdate :one
SELECT id::text, household_id::text, created_by_user_id::text, creation_key, token_hash, created_at, expires_at, accepted_at, revoked_at
FROM household_invitations WHERE token_hash=$1 FOR UPDATE
`

type FindInvitationByTokenForUpdateRow struct {
	ID              string
	HouseholdID     string
	CreatedByUserID string
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) FindInvitationByTokenForUpdate(ctx context.Context, tokenHash []byte) (FindInvitationByTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findInvitationByTokenForUpdate, tokenHash)
	var i FindInvitationByTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedByUserID,
		&i.CreationKey,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findLoginForInvitation = `-- name: FindLoginForInvitation :one
SELECT id::text FROM user_accounts WHERE login=$1
`

func (q *Queries) FindLoginForInvitation(ctx context.Context, login string) (string, error) {
	row := q.db.QueryRow(ctx, findLoginForInvitation, login)
	var id string
	err := row.Scan(&id)
	return id, err
}

const invitationExistsInHousehold = `-- name: InvitationExistsInHousehold :one
SELECT EXISTS(SELECT 1 FROM household_invitations WHERE household_id=$1 AND id=$2)
`

type InvitationExistsInHouseholdParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) InvitationExistsInHousehold(ctx context.Context, arg InvitationExistsInHouseholdParams) (bool, error) {
	row := q.db.QueryRow(ctx, invitationExistsInHousehold, arg.HouseholdID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id::text, household_id::text, created_by_user_id::text, creation_key, token_hash, created_at, expires_at, accepted_at, revoked_at
FROM household_invitations WHERE household_id=$1 AND ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id LIMIT $3
`

type ListInvitationsParams struct {
	HouseholdID pgtype.UUID
	Column2     pgtype.UUID
	Limit       int32
}

type ListInvitationsRow struct {
	ID              string
	HouseholdID     string
	CreatedByUserID string
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.HouseholdID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CreatedByUserID,
			&i.CreationKey,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForInvitation = `-- name: LockUserForInvitation :one
SELECT id::text, login, COALESCE(default_household_id::text, '')::text AS default_household_id FROM user_accounts WHERE id=$1 FOR UPDATE
`

type LockUserForInvitationRow struct {
	ID                 string
	Login              string
	DefaultHouseholdID string
}

func (q *Queries) LockUserForInvitation(ctx context.Context, id pgtype.UUID) (LockUserForInvitationRow, error) {
	row := q.db.QueryRow(ctx, lockUserForInvitation, id)
	var i LockUserForInvitationRow
	err := row.Scan(&i.ID, &i.Login, &i.DefaultHouseholdID)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE household_invitations SET revoked_at=$3 WHERE household_id=$1 AND id=$2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $3
`

type RevokeInvitationParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.HouseholdID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
