// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID        pgtype.UUID
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}

type HouseholdMembership struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	Role        string
}

type InstallationState struct {
	Singleton     bool
	SetupRequired bool
}

type LocalCredential struct {
	UserID       pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type UserAccount struct {
	ID                 pgtype.UUID
	Login              string
	DefaultHouseholdID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type UserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
