// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID        pgtype.UUID
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type HouseholdInvitation struct {
	ID              pgtype.UUID
	HouseholdID     pgtype.UUID
	CreatedByUserID pgtype.UUID
	CreationKey     string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type HouseholdMembership struct {
	UserID      pgtype.UUID
	HouseholdID pgtype.UUID
	Role        string
}

type InstallationState struct {
	Singleton     bool
	SetupRequired bool
}

type Item struct {
	ID                pgtype.UUID
	HouseholdID       pgtype.UUID
	SubjectID         pgtype.UUID
	Title             string
	Notes             pgtype.Text
	AttentionOn       pgtype.Date
	WorkflowState     string
	Archived          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
	ResponsibleUserID pgtype.UUID
}

type LocalCredential struct {
	UserID       pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type OidcFlow struct {
	StateHash        []byte
	BrowserTokenHash []byte
	Issuer           string
	ClientID         string
	Nonce            string
	PkceVerifier     string
	Purpose          string
	UserID           pgtype.UUID
	SessionID        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}

type OidcIdentity struct {
	Issuer    string
	Subject   string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Subject struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type UserAccount struct {
	ID                 pgtype.UUID
	Login              string
	DefaultHouseholdID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type UserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
