// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOIDCFlow = `-- name: ConsumeOIDCFlow :one
DELETE FROM oidc_flows WHERE state_hash=$1 AND browser_token_hash=$2 AND expires_at>$3 AND issuer=$4 AND client_id=$5
RETURNING issuer,client_id,nonce,pkce_verifier,purpose,COALESCE(user_id::text,'')::text AS user_id,COALESCE(session_id::text,'')::text AS session_id,created_at,expires_at
`

type ConsumeOIDCFlowParams struct {
	StateHash        []byte
	BrowserTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	Issuer           string
	ClientID         string
}

type ConsumeOIDCFlowRow struct {
	Issuer       string
	ClientID     string
	Nonce        string
	PkceVerifier string
	Purpose      string
	UserID       string
	SessionID    string
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) ConsumeOIDCFlow(ctx context.Context, arg ConsumeOIDCFlowParams) (ConsumeOIDCFlowRow, error) {
	row := q.db.QueryRow(ctx, consumeOIDCFlow,
		arg.StateHash,
		arg.BrowserTokenHash,
		arg.ExpiresAt,
		arg.Issuer,
		arg.ClientID,
	)
	var i ConsumeOIDCFlowRow
	err := row.Scan(
		&i.Issuer,
		&i.ClientID,
		&i.Nonce,
		&i.PkceVerifier,
		&i.Purpose,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOIDCFlowForPreviousBrowser = `-- name: DeleteOIDCFlowForPreviousBrowser :exec
DELETE FROM oidc_flows WHERE browser_token_hash=$1
`

func (q *Queries) DeleteOIDCFlowForPreviousBrowser(ctx context.Context, browserTokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteOIDCFlowForPreviousBrowser, browserTokenHash)
	return err
}

const findOIDCCredential = `-- name: FindOIDCCredential :one
SELECT password_hash FROM local_credentials WHERE user_id=$1
`

func (q *Queries) FindOIDCCredential(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, findOIDCCredential, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const findOIDCIdentity = `-- name: FindOIDCIdentity :one
SELECT user_id::text AS user_id FROM oidc_identities WHERE issuer=$1 AND subject=$2
`

type FindOIDCIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) FindOIDCIdentity(ctx context.Context, arg FindOIDCIdentityParams) (string, error) {
	row := q.db.QueryRow(ctx, findOIDCIdentity, arg.Issuer, arg.Subject)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const insertOIDCFlow = `-- name: InsertOIDCFlow :exec
INSERT INTO oidc_flows(state_hash,browser_token_hash,issuer,client_id,nonce,pkce_verifier,purpose,user_id,session_id,created_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertOIDCFlowParams struct {
	StateHash        []byte
	BrowserTokenHash []byte
	Issuer           string
	ClientID         string
	Nonce            string
	PkceVerifier     string
	Purpose          string
	UserID           pgtype.UUID
	SessionID        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) InsertOIDCFlow(ctx context.Context, arg InsertOIDCFlowParams) error {
	_, err := q.db.Exec(ctx, insertOIDCFlow,
		arg.StateHash,
		arg.BrowserTokenHash,
		arg.Issuer,
		arg.ClientID,
		arg.Nonce,
		arg.PkceVerifier,
		arg.Purpose,
		arg.UserID,
		arg.SessionID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const linkedOIDCIdentity = `-- name: LinkedOIDCIdentity :one
SELECT EXISTS(SELECT 1 FROM oidc_identities WHERE user_id=$1 AND issuer=$2)
`

type LinkedOIDCIdentityParams struct {
	UserID pgtype.UUID
	Issuer string
}

func (q *Queries) LinkedOIDCIdentity(ctx context.Context, arg LinkedOIDCIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, linkedOIDCIdentity, arg.UserID, arg.Issuer)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pruneOIDCFlows = `-- name: PruneOIDCFlows :exec
DELETE FROM oidc_flows WHERE expires_at <= $1
`

func (q *Queries) PruneOIDCFlows(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneOIDCFlows, expiresAt)
	return err
}
