// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions(user_id,token_hash,created_at,expires_at) VALUES($1,$2,$3,$4) RETURNING id::text AS id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions WHERE user_id=$1 AND expires_at <= $2
`

type DeleteExpiredSessionsParams struct {
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE token_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const findActiveSession = `-- name: FindActiveSession :one
SELECT s.id::text AS id, u.id::text AS user_id, u.login, COALESCE(u.default_household_id::text, '')::text AS default_household_id, s.expires_at
FROM user_sessions s JOIN user_accounts u ON u.id=s.user_id
WHERE s.token_hash=$1 AND s.expires_at>$2
`

type FindActiveSessionParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type FindActiveSessionRow struct {
	ID                 string
	UserID             string
	Login              string
	DefaultHouseholdID string
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) FindActiveSession(ctx context.Context, arg FindActiveSessionParams) (FindActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, findActiveSession, arg.TokenHash, arg.ExpiresAt)
	var i FindActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Login,
		&i.DefaultHouseholdID,
		&i.ExpiresAt,
	)
	return i, err
}

const findLogin = `-- name: FindLogin :one
SELECT u.id::text AS user_id, u.login, COALESCE(u.default_household_id::text, '')::text AS default_household_id, c.password_hash
FROM user_accounts u JOIN local_credentials c ON c.user_id=u.id WHERE u.login=$1
`

type FindLoginRow struct {
	UserID             string
	Login              string
	DefaultHouseholdID string
	PasswordHash       string
}

func (q *Queries) FindLogin(ctx context.Context, login string) (FindLoginRow, error) {
	row := q.db.QueryRow(ctx, findLogin, login)
	var i FindLoginRow
	err := row.Scan(
		&i.UserID,
		&i.Login,
		&i.DefaultHouseholdID,
		&i.PasswordHash,
	)
	return i, err
}

const memberLogins = `-- name: MemberLogins :many
SELECT id::text AS user_id, login FROM user_accounts WHERE id = ANY($1::uuid[])
`

type MemberLoginsRow struct {
	UserID string
	Login  string
}

func (q *Queries) MemberLogins(ctx context.Context, dollar_1 []pgtype.UUID) ([]MemberLoginsRow, error) {
	rows, err := q.db.Query(ctx, memberLogins, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberLoginsRow{}
	for rows.Next() {
		var i MemberLoginsRow
		if err := rows.Scan(&i.UserID, &i.Login); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
