// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setup.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSetup = `-- name: CompleteSetup :exec
UPDATE installation_state SET setup_required = false WHERE singleton = true
`

func (q *Queries) CompleteSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, completeSetup)
	return err
}

const createLocalCredential = `-- name: CreateLocalCredential :exec
INSERT INTO local_credentials (user_id, password_hash) VALUES ($1, $2)
`

type CreateLocalCredentialParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateLocalCredential(ctx context.Context, arg CreateLocalCredentialParams) error {
	_, err := q.db.Exec(ctx, createLocalCredential, arg.UserID, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user_accounts (login) VALUES ($1) RETURNING id::text
`

func (q *Queries) CreateUser(ctx context.Context, login string) (string, error) {
	row := q.db.QueryRow(ctx, createUser, login)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockSetupState = `-- name: LockSetupState :one
SELECT setup_required FROM installation_state WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockSetupState(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockSetupState)
	var setup_required bool
	err := row.Scan(&setup_required)
	return setup_required, err
}

const setDefaultHousehold = `-- name: SetDefaultHousehold :exec
UPDATE user_accounts SET default_household_id = $2 WHERE id = $1
`

type SetDefaultHouseholdParams struct {
	ID                 pgtype.UUID
	DefaultHouseholdID pgtype.UUID
}

func (q *Queries) SetDefaultHousehold(ctx context.Context, arg SetDefaultHouseholdParams) error {
	_, err := q.db.Exec(ctx, setDefaultHousehold, arg.ID, arg.DefaultHouseholdID)
	return err
}
