// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (CreateSubjectRow, error)
	GetSubject(ctx context.Context, arg GetSubjectParams) (GetSubjectRow, error)
	ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]ListSubjectsRow, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (UpdateSubjectRow, error)
}

var _ Querier = (*Queries)(nil)
