// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subject.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (household_id, type, name)
VALUES ($1, $2, $3)
RETURNING id::text AS id, household_id::text AS household_id, type, name, archived, created_at, updated_at, version
`

type CreateSubjectParams struct {
	HouseholdID pgtype.UUID
	Type        string
	Name        string
}

type CreateSubjectRow struct {
	ID          string
	HouseholdID string
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (CreateSubjectRow, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.HouseholdID, arg.Type, arg.Name)
	var i CreateSubjectRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Type,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSubject = `-- name: GetSubject :one
SELECT id::text AS id, household_id::text AS household_id, type, name, archived, created_at, updated_at, version
FROM subjects
WHERE household_id = $1 AND id = $2
`

type GetSubjectParams struct {
	HouseholdID pgtype.UUID
	ID          pgtype.UUID
}

type GetSubjectRow struct {
	ID          string
	HouseholdID string
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (GetSubjectRow, error) {
	row := q.db.QueryRow(ctx, getSubject, arg.HouseholdID, arg.ID)
	var i GetSubjectRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Type,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id::text AS id, household_id::text AS household_id, type, name, archived, created_at, updated_at, version
FROM subjects
WHERE household_id = $1 AND archived = $2 AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListSubjectsParams struct {
	HouseholdID pgtype.UUID
	Archived    bool
	AfterID     pgtype.UUID
	RowLimit    int32
}

type ListSubjectsRow struct {
	ID          string
	HouseholdID string
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects,
		arg.HouseholdID,
		arg.Archived,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectsRow{}
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Type,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = COALESCE($1::text, name),
    type = COALESCE($2::text, type),
    archived = COALESCE($3::boolean, archived),
    version = version + 1,
    updated_at = now()
WHERE household_id = $4 AND id = $5 AND version = $6
RETURNING id::text AS id, household_id::text AS household_id, type, name, archived, created_at, updated_at, version
`

type UpdateSubjectParams struct {
	Name            pgtype.Text
	Type            pgtype.Text
	Archived        pgtype.Bool
	HouseholdID     pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int64
}

type UpdateSubjectRow struct {
	ID          string
	HouseholdID string
	Type        string
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (UpdateSubjectRow, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Name,
		arg.Type,
		arg.Archived,
		arg.HouseholdID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateSubjectRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Type,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
